[general]
import = ["./themes/github-dark.toml"]
live_config_reload = true

[window]
#decorations="None"
decorations_theme_variant = "Dark"
padding = {x = 10, y = 0}
dynamic_padding = true

[font]
normal.family = "MesloLGS Nerd Font"
#normal.family = "Noto Color Emoji"
size = 11.5

[colors]
draw_bold_text_with_bright_colors = true
cursor = { text = "#000000", cursor = "#7ec3c1" }
vi_mode_cursor = { text = "#000000", cursor = "#01a0e4"}
#line_indicator = { foreground = "#f7f3f7", background = "#1b181b" }
footer_bar = { foreground = "#b5e4f4", background = "#090300" }
selection = { text = "#a5a2a2", background = "#000000" }

[bell]	
animation = "EaseOutExpo"
duration = 500
color = "#000000"
#command = { program = "notify-send", args = ["Bell"] }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Never" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false
thickness = 0.1

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	{ key = "V", mods = "Control", action = "ToggleViMode" },
]
